### ISSUE TITLE
Documentation outdated

### ISSUE THREAD

**Issue by kerrhome** [foxpass/foxpass-setup#48]
Can you update your documentation to include Debian 10 here: https://docs.foxpass.com/docs/debian-9 ?

Also, can you please add support for Debian 11 Bullseye?  We were forced to use it because we had a box that was better supported by the newest OS (I know, not officially released yet).  I'm going to try the debian-10 script in a docker image first to see how that goes.

**Comment by kerrhome** [comment]
btw, the `debian-10` script worked fine for me on a bullseye docker image (I used `bullseye-20210111-slim`).
with
```
touch /etc/netgroup
apt install -y wget python python-pip sudo openssh-server
pip install urllib3
```

**Comment by aren** [comment]
I updated the docs for debian 10. For bullseye, was the `touch /etc/netgroup` required before the install would succeed?

**Comment by shanzez** [comment]
Thanks much, sir.  Well, I don't think anything was broken because of the non-existent `/etc/netgroup`, but it threw me for a minute.  Once I realized it was just complaining about monitoring a file that wasn't there and there was no actual failure, I could have just ignored it.  Someone else might see the message and thing something was broken.  Touching it into existence just makes it all clean and nothing but success messages.  Shorter: it's unnecessary, but clean if you do it.

**Comment by kerrhome** [comment]
Sorry about that.  Switched back to my personal account (from work account).  Thanks again for the updates.
